[general]
live_config_reload = true
import = ["~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control"

[scrolling]
history = 5000

[window]
dynamic_padding = false
decorations_theme_variant = "light"
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
